### PR TITLE
Update to main branch + switch to fw-ectool

### PR DESCRIPTION
**Pull request by Svenum**
On nixpkgs are two ectools:
-> ectool: the default ectool
-> fw-ectool: the ectool from DHowett modified for framework

So I am switching to the framework one.

There was merge conflicts in the fanctrl.py and I am not sure if I merged it correctly. Please review it. I will test this build later this day.

### CODE REVIEW

**Comment by Svenum** [comment]
Works great, but `fw-fanctrl -q` and `fw-fanctrl --list-strategies` does not output anything. Changing the strategy works fine. Any Ideas?

**Comment by leopoldhub** [comment]
I'll check that in ~4h, thanks for your hard work

**Comment by Svenum** [comment]
> Works great, but `fw-fanctrl -q` and `fw-fanctrl --list-strategies` does not output anything. Changing the strategy works fine. Any Ideas?

I checked the diff between the fanctrl.py on main an my branch. They are the same. So thats not the problem.

**Comment by Svenum** [comment]
> Works great, but `fw-fanctrl -q` and `fw-fanctrl --list-strategies` does not output anything. Changing the strategy works fine. Any Ideas?

I think its the same as https://github.com/TamtamHero/fw-fanctrl/issues/62

**Comment by leopoldhub** [comment]
Hi, sorry for the inconvenience.
It was fixed in #63

**Review by leopoldhub — APPROVED** [review]
I cannot test nix related stuff, but otherwise it looks good to me!

**Comment by Svenum** [comment]
Nice, then I update a list time to the state of the main branch and make the PR ready to merge

**Review by leopoldhub — APPROVED** [review]
Hi, sorry for the delay, everything looks good to me, is this ready for merge ?

**Comment by Svenum** [comment]
Yes, it's ready.  :+1:

**Pull request merged**
