### PR TITLE
Separating FanController into different subclasses to allow HardwareController and SocketController diversity.

### PR DESCRIPTION
**Pull request by leopoldhub**
separating `FanController` into different subclasses to allow `HardwareController` and `SocketController` diversity.
This should make things easier for #47 and windows support #30 .

### CODE REVIEW

**Comment by leopoldhub** [comment]
Hi @TamtamHero , I hope you are doing well.

Could you please double check this one if you have some time?

Have a great day!

**Comment by TamtamHero** [comment]
Hello @leopoldhub !
I'm a bit late to the party, sorry
Can you detail a little more why supporting 2 methods is useful, vs being opiniated on picking a single one ?
The issue #47 mentions "It would allow those unhappy with the supplied binary to use the kernel module instead." 
Who isn't happy with ectool, actually ? There was some issues with ectool not being up to date for latest models, but it was my mistake and it should not happen again. What am I missing ?
For issue #30, can you also explain how this PR would help (have you been able to try ectool on WIndows ? Does it work there ?)

**Comment by leopoldhub** [comment]
Hi @TamtamHero ,
Thanks for the quick reply!

I think that #47 was originally created because people don't like having binary blobs in repositories (which I can understand). #51 should fix that, and #47 may become irrelevant.

> For issue https://github.com/TamtamHero/fw-fanctrl/issues/30, can you also explain how this PR would help

Unix sockets don't work on Windows, and this extraction will make it easier to implement Windows-specific ones (same goes if we can't use ectool and have to use some other method).

> (have you been able to try ectool on WIndows ? Does it work there ?)

Someone I know got it to work on a Framework 13 with Windows 10, I should receive my secondary SSD soon and will be able to try it by myself.

I hope this answer your questions ^^

**Comment by TamtamHero** [comment]
Okay, so thanks to your work on #51 the only remaining reason to implement this would be in the case where ectool is not working correctly on Windows ?
Then, the way I see it, it's better to wait until we check this before adding these changes, because there is a chance that we don't actually need them 
What do you think ?

**Comment by leopoldhub** [comment]
Sure, the socket controller will definitely be needed, but the hardware one should not (I hope).

Features aside, I also like the fact that there are separate components with a specific purpose.
This prevents us from using the ectool in a place where it should not be, and makes the individual components (especially the fan controller) lighter and easier to read.

**Review by TamtamHero — APPROVED** [review]

**Comment by leopoldhub** [comment]
Hi @TamtamHero , how was your day?

I received my SSD, and managed to use the ectool with Windows.
I had a bit of trouble getting it to work due to the difference in behaviour between how Windows and Linux and had the great help of Dustin (@DHowett) to help me troubleshoot.

With this, the only missing piece is a Windows socket equivalent, and we should be good for a Windows version!

**Comment by TamtamHero** [comment]
Very nice, well done !
Glad to hear that, Dustin helps again <3

About this PR, frankly you can forget what I wrote before it's garbage, I didn't get what you were doing here 
It's all good :+1:

From 15 seconds of googling, it looks like Windows has added support for AF_UNIX sockets in 2017, so maybe there's no code to write at all ? :angel:

**Comment by leopoldhub** [comment]
> Glad to hear that, Dustin helped again <3
Yes, he is the GOAT

> About this PR, frankly you can forget what I wrote before it's garbage, I didn't get what you were doing here It's all good 👍
No, don't worry about that, It's all good too 👍

> From 15 seconds of googling, it looks like Windows has added support for AF_UNIX sockets in 2017, so maybe there's no code to write at all ? 👼
it would indeed be very nice not having to re-implement the sockets

**Comment by leopoldhub** [comment]
@TamtamHero 
I... messed up...
I synced my dev branch with this repo main one without thinking much and happily deleted my work 🫠...
Will have to to it again... yay...

**Comment by DHowett** [comment]
@leopoldhub hey, you can still get your work back!

https://github.com/TamtamHero/fw-fanctrl/commit/f7b91691f5aaae83d50cc32155686db421b81076

f7b91691f5aaae83d50cc32155686db421b81076

**Comment by leopoldhub** [comment]
@DHowett the GOAT as usual 🎉
Got the work back!
Will have to create a new PR though

**Comment by DHowett** [comment]
@leopoldhub aw, thanks.

You can force push that commit back to this PR with...

```
git push https://github.com/leopoldhub/fw-fanctrl.git f7b9169:refs/heads/dev
```

**Comment by leopoldhub** [comment]
Thanks a lot, unfortunately it didn't work ("Everything up-to-date")
I will create a new pr and link it to this one

**Comment by DHowett** [comment]
Alas! Sorry that didn't work out.

**Pull request closed without merging**
