### PR TITLE
Add choice to print fan speed percentage

### LINKED ISSUE #74: [FEATURE] `print` command option for current fan speed
**Is your feature request related to a problem? Please describe.**

Currently there are only two supported options for the `print` command: `list` and `current`. At the moment I'm not using separate strategies for charging and discharging so, these two options aren't particularly relevant for me. What I am interested in printing is the current fan speed percentage and/or exact RPM.

**Describe the solution you'd like**

Additional supported arguments for the `print` command to monitor the current fan speed, such as:
```sh
$ fw-fanctrl print speed_percentage
23
```
and/or
```sh
$ fw-fanctrl print speed_rpm
672
```
No strong preferences on the naming of the arguments

**Describe alternatives you've considered**

I _could_ get the current fan speed by extracting it from the log messages, but the current fan speed feels like it should be a valid option supported by the script

**Additional context**

My exact use case is to add a custom fan speed module to my waybar setup. Having a concise command able to print the value to display makes it much more simple to configure:
```json
{
  "custom/fan-speed": {
    "exec": "fw-fanctrl print speed_percentage",
    "format": "{}%",
    "interval": 5
  }
}
```

**Would you like to be involved in the development?**
Sure! Python is not my strong suit, though. I believe I could come up with an implementation that does work, but it might not be the "right" way to do it

### PR DESCRIPTION
**Pull request by Speenah**
Adds an option to print the current fan speed percentage:

```
$ fw-fanctrl print speed
23%
```

Turns out adding the percentage was pretty trivial since the `FanController` holds this state. Printing the current RPM is slightly more complex since it needs to be retrieved from the hardware controller, and can be ambiguous on how to handle the case of multiple fans. But just getting the percentage satisfies my original use case

Closes #74

### CODE REVIEW

**Review by leopoldhub — COMMENTED** [review]
Hi,

Thanks for your contribution.

As you have added an extra description for each choice in the documentation, do you think you could do the same in the parser?

Otherwise, everything seems fine to me!

**Comment by Speenah** [comment]
Sure! Would that be to edit the `help` argument on the `printCommand.add_argument`? I'm looking at the [docs for choices](https://docs.python.org/3/library/argparse.html#choices) and I'm not seeing a way to specify a description for each choice

**Comment by leopoldhub** [comment]
Yes, sadly there is no other option than editing the global help.
The parser already have the `RawTextHelpFormatter` formatter class, so you should be able to use `\n` to create new lines.

**Comment by Speenah** [comment]
With c08e559 the output looks like this
```
positional arguments:
  {current,list,speed}  current - The current strategy
                        list - List available strategies
                        speed - The current fan speed percentage
```

**Review by leopoldhub — APPROVED** [review]
Everything seems fine to me.

Thank you for your time and contribution, have a nice day!

**Pull request merged**
