### PR TITLE
Update branch to main branch

### PR DESCRIPTION
**Pull request by Svenum**
I have updated the `nix/packaging` branch to align with the main branch + removed the ectool dependencie. I use the ectool from the nixpkgs repo.

If I forgot some features to add in the nix module that got added please inform me here. :smile:

### CODE REVIEW

**Comment by leopoldhub** [comment]
Hi, thanks for your hard work!

I will check your work when I have some time.
Could you please change the target branch to packaging/nix instead of main?

Have a nice day!

**Comment by Svenum** [comment]
I miss clicked the brach 🤦‍♂️. I will wait for your feedback :+1:

**Review by leopoldhub — APPROVED** [review]
Seems good on my side 👍

**Comment by leopoldhub** [comment]
Thanks again for your work, have a nice day!

**Pull request merged**
