### PR TITLE
Add ToC + link to NixOS Documentation

### PR DESCRIPTION
**Pull request by Svenum**
I have added the doc folder, so that:
- the documentation is better sorted
- the documentation more modular
- all the documentation is on the same place and not scattered over multiple branches
- the repo README.md is not so overloaded
- updating the `packaging` branches do not interfere with the README.md in the main branch

### CODE REVIEW

**Comment by leopoldhub** [comment]
Hi, thanks for all your hard work.

I have a slight problem though, I am working on a windows branch that has its own versions of "installation", "update", "configuration"...
And it does not integrate well with the structure you provide.

Also, while I appreciate clear and organised global documentation, I feel that important information such as installation and basic configuration should be readily available to the user without being hidden it behind a link.

Here is my suggestion to solve this problem.

I think we should have basic and important documentation in the readme, as we already have, as well as a documentation structure specific to each branch.
On the main documentation page, we could add links to other branches' documentation to redirect the user to their preferred packaging/platform.

What do you think?

**Comment by Svenum** [comment]
Mhmmm....

- **Windows branch**:
  Ok, that information is new to me, so I suggest to make a linux doc and a windows doc. So we can seperate those documentations.
  Something like:
  - `/doc/linux/building.md` and `/doc/windows/building.md`
  - `/doc/linux/configuration.md` and `/doc/windows/documentation.md`
  - `/doc` for the global information like _commands_.
- **Documentation on the main README**:
  Sorry, but I disagree on that. I think the main README must provide clear and simple information about what the project is about and to show global important information such as features, what is at the moment worked on and **a clear and simple way how to get to the documentation**, but not the documentation it self. Else the README get longer and longer when more features are introduced.
- **Links to the packaging documentation**:
  I agree on that to 100%. I would add a link to that specific packaging doc in the main branch to the main README as I have already done to the NixOS doc.
  
Sorry that I disagree, but I do not like the idea of splitting of the documentation over multiple branches and the longer and longer getting README.
I think that a long README makes a bad first impression for users that are not so technically as we are. They want a simple doc and not find the needed point in an essay.

**Comment by leopoldhub** [comment]
> Sorry that I disagree

Don't be sorry, we are here to share our opinions and everyone is free to express theirs.

> I suggest to make a linux doc and a windows doc. So we can seperate those documentations.

The main problem I have with this approach is that in order to edit the windows documentation, we have to make the changes on the main branch and then merge it with the windows branch (we will never merge a packaging branch to main).

> I think the main README must provide clear and simple information about what the project is about and to show global important information such as features, what is at the moment worked on and a clear and simple way how to get to the documentation, but not the documentation it self. Else the README get longer and longer when more features are introduced.

I agree that advanced documentation should be extracted from the readme.
However, the majority of the repo visitors come here to install the script, and I think it is important to have concise and clear instructions on how to do it, so they do not have to search the documentation (for advanced installation arguments, we can still have a link to the documentation of course).

In the wild, most non-technical, user-oriented projects have some version of this.
For those that have packages (e.g. android, linux...) this is often a link to the release or store, but those that do not, have a small part dedicated to installation.

https://github.com/TagStudioDev/TagStudio#installation
https://github.com/pbek/QOwnNotes#installation
https://github.com/fast4x/RiMusic#-installation

> I think that a long README makes a bad first impression for users that are not so technically as we are

I completely agree with this, and I think it makes my previous point even more relevant, as we should facilitate the installation process.

**Comment by Svenum** [comment]
> The main problem I have with this approach is that in order to edit the windows documentation, we have to make the changes on the main branch and then merge it with the windows branch (we will never merge a packaging branch to main).

Thats true. I doesn't think about that. 

> I agree that advanced documentation should be extracted from the readme. However, the majority of the repo visitors come here to install the script, and I think it is important to have concise and clear instructions on how to do it, so they do not have to search the documentation (for advanced installation arguments, we can still have a link to the documentation of course).

Ok, then we need a table of content at the Top of the README, so that you can find easily the chapter you searching for. 



So what is to do:
- Adding ToC at the top of the main README
- Adding the doc folder to the packaging branches and add the packaging specific documentation there, so that the main README is same over all branches.
- Update the Link in the main README to the packaging docs

Is that right or does I miss something?

**Comment by leopoldhub** [comment]
While I still believe we should put the main installation command in clear in the readme,
I think this new approach should be good for now 👍.

**Comment by Svenum** [comment]
I could do this, and add it to the ToC. So it stays more clear, even if its long.

**Comment by leopoldhub** [comment]
I would appreciate that (if it is still too messy, we can always remove it later)

**Comment by Svenum** [comment]
I added the ToC. and the new url to the Nix Flake doc

**Comment by Svenum** [comment]
If this PR is created I will rebase the packaging/nix branch on this, so that all the file on the same state and then I add the doc file in the repo.

**Comment by Svenum** [comment]
So this PR is ready now, if you agree with the changes :)

**Comment by leopoldhub** [comment]
Hey, sorry if I misunderstood, didn't you want to extract every technical documentation to the doc folder (except for the basic installation instructions)?

**Comment by Svenum** [comment]
Sorry if I misunderstood. I thought you want to keep the hole readme and just add the toc at first and later sort it in the doc folder. I am fine with both. My main goal was to keep this file same over all branches. And thats given.

**Comment by leopoldhub** [comment]
Yeah, a bit of miscommunication here 😅, sorry

If you want to keep it (mostly) the same on all branches, better move the heavy part of the documentation now

**Comment by Svenum** [comment]
No problem. It was my fault too. XD

So is it now how we both expect it?

**Comment by leopoldhub** [comment]
Yes, just make sure that there is a blank line under each title/subtitle and we should be good for now.

I will think about whether we should move the actual "installation" doc to a separate page while replacing it in the readme with a more concise explanation or not for a future PR.

**Comment by Svenum** [comment]
> Yes, just make sure that there is a blank line under each title/subtitle and we should be good for now.
Done, I hope I havent forget any line. :smile:

**Review by leopoldhub — APPROVED** [review]
Perfect, thanks a lot for this, have a nice day!

**Pull request merged**
