### PR TITLE
Separating FanController into different subclasses to allow HardwareController and SocketController diversity. 2 (Repost of #50)

### PR DESCRIPTION
**Pull request by leopoldhub**
Repost of #50 because I am stupid 🫠 and lost my work (@DHowett the GOAT)

### CODE REVIEW

**Review by TamtamHero — APPROVED** [review]

**Comment by belden** [comment]
@leopoldhub Hello! I wonder if this is mergeable?

**Comment by belden** [comment]
fyi I came here via https://github.com/TamtamHero/fw-fanctrl/pull/47

**Comment by leopoldhub** [comment]
Hi @belden , it should be, I will test it once more to be sure.

**Comment by leopoldhub** [comment]
@belden @TamtamHero
It is now, could I have one last check before the merge?

**Comment by TamtamHero** [comment]
All good 👍

**Pull request merged**
