### PR TITLE
README.md documentation update

### PR DESCRIPTION
**Pull request by leopoldhub**

### CODE REVIEW

**Comment by leopoldhub** [comment]
I also includes two minor commits to:

1. force socket encoding to utf-8
2. change the log format on fatal crash

**Comment by leopoldhub** [comment]
Hi @TamtamHero ,
Hope this finds you well

It looks like you're busy, sorry if these messages may seem a bit overwhelming 😅

As they don't have much impact on features and compatibility, I'm going to take the liberty of merging this PR as well as #66, so that I can continue working on the Windows branch and external projects while waiting for your approval.

Have a nice day

**Comment by TamtamHero** [comment]
I was offline for a month, didn't even thought about letting you know, sorry
I'll catch up in the next days !

**Comment by leopoldhub** [comment]
Hi @TamtamHero 

No problem, I hope you are doing well.
I will be mostly monitoring thing this month as well, I am busy with work related stuff.

If you disagree with any decision I have made in your absence, please let me know, and I will do my best to rectify it.

Have a nice day.

**Pull request merged**
